### ISSUE TITLE
Support input type='hidden'

### ISSUE THREAD

**Issue by jpeterson** [wyuenho/backgrid-select2-cell#7]
Would love to see support for using hidden `input` element instead of a `select` element. This will enable a few advanced features of Select2 - the most obvious one being tagging support.

Currently, attempting to use the `tags` option in `select2Options` results in the following error (since the element is always a `select`:

`Option 'tags' is not allowed for Select2 when attached to a <select> element.`

**Comment by wyuenho** [comment]
select2 4.x will have solved this problem.
