### ISSUE TITLE
0.3.6 Fail with AMD

### ISSUE THREAD

**Issue by jonapgar** [wyuenho/backgrid-select2-cell#9]
0.3.6 throws an error on loading when using requirejs. 

This factory function expects three params: **root**, **_** and **Backgrid**, but only **_** and **Backgrid** are passed to the factory function when using AMD. 

In addition, and perhaps more importantly, when downloading this module via Bower and specifying version 0.3.5 I get a mismatch and the 0.3.6 version is downloaded. When we deploy our software that uses this module we download the broken 0.3.6 version even when specifying 0.3.5 in bower.json

From Bower:

`bower backgrid-select2-cell#*              mismatch Version declared in the json (0.3.5) is different than the resolved one (0.3.6)
bower backgrid-select2-cell#~0.3.5         mismatch Version declared in the json (0.3.5) is different than the resolved one (0.3.6)`

**Comment by wyuenho** [comment]
I just released 0.3.7. Give it a try.

**Comment by wyuenho** [comment]
Actually gimme a few more minutes.

**Comment by wyuenho** [comment]
Should be good now.

**Comment by jonapgar** [comment]
Looks good now thanks!
